name: CI Lint

on:
  pull_request:
  push:

env:
  PYTHON_VERSION: "3.14"

jobs:
  lint-no-cyrillic-and-emoji:
    runs-on: python:3.14.0
    container:
      image: ghcr.io/dubovsky-andrey/k8s-ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cyrillic/Emoji Linter
        run: python3 scripts/lint.py .